<a href="https://colab.research.google.com/github/gabis0604/projetos-da-faculdade-linguagem-de-sistemas/blob/main/Unid3_aul_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##AULA 02 UNIDADE 3

In [1]:
import pandas as pd

exemplo1 = [10, 20, 30, 40, 50]
print(type(exemplo1))

<class 'list'>

In [3]:
series1 = pd.Series(data=exemplo1)
print(type(series1))

<class 'pandas.core.series.Series'>

In [4]:
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
exemplo2 = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series2 = pd.Series(data=exemplo2)
print(series2)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [6]:
print("Media:", series2.mean())
print("Soma:", series2.sum())
print("Maximo:", series2.max())
print("Minimo:", series2.min())

Media: 30.0
Soma: 150
Maximo: 50
Minimo: 10

In [10]:
import pandas as pd

url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
dfs = pd.read_html(url)
print(type(dfs))
print(len(dfs))

<class 'list'>
1

In [11]:
df_bancos = dfs[0]

print("Dimensões (linha, colunas):", df_bancos.shape)
print("\ntipos de cada coluna:")
print(df_bancos.dtypes)
print("\nPrimeiras 5 linhas:")
df_bancos.head()

Dimensões (linha, colunas): (25, 7)

tipos de cada coluna:
Bank Name                object
City                     object
State                    object
Cert                      int64
Acquiring Institution    object
Closing Date             object
Fund  Sort ascending      int64
dtype: object

Primeiras 5 linhas:

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

In [13]:
df = pd.read_csv("ipeadata[21-09-2026-11-44].csv")

In [14]:
df.head()

                     Arrecadação do IPTU incluindo receitas da dívida ativa e de multas e juros - INATIVA
Sigla Código Brasil                                                NaN
BR    0      Brasil                                                NaN

In [15]:
import pandas as pd

dados = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
    'Idade': [25, 30, 35, 40],
}

serie_idades = pd.Series(dados['Idade'], index=dados['Nome'])

print("Serie de Idades: ")
print(serie_idades)

media_idades = serie_idades.mean()
print(f"\nMedia das Idades: , {media_idades}")

print(f"\nMaior Idade: {serie_idades.max()}")
print(f"Menor Idade: {serie_idades.min()}")

Serie de Idades:
Alice      25
Bob        30
Charlie    35
David      40
dtype: int64

Media das Idades: , 32.5

Maior Idade: 40
Menor Idade: 25